title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://hancocb.github.io/jtd.template.github.io

aux_links:
  Template Repository: https://github.com/hancocb/jtd.template.github.io
